In [22]:
import numpy as np
from desdeo_problem.surrogatemodels.lipschitzian import LipschitzianRegressor
from optproblems.dtlz import DTLZ2

In [3]:
prob = DTLZ2(num_variables=10, num_objectives=2)

In [4]:
x = np.random.rand(109,10)
y= np.asarray([prob(xi) for xi in x])

In [6]:
model = LipschitzianRegressor()

In [15]:
model.fit(x,y[:,0].reshape(-1,1))

In [16]:
model.predict(x[1:5,:])

(array([1.61873996, 1.85664825, 0.86734006, 2.00172108]),
 array([0., 0., 0., 0.]))

In [14]:
x[1:5,:]

array([[0.06222891, 0.56952977, 0.72232353, 0.07503399, 0.99067493,
        0.29306293, 0.5142018 , 0.63831188, 0.20430749, 0.53598978],
       [0.08840214, 0.2497215 , 0.33743208, 0.08521341, 0.06660252,
        0.15871699, 0.33923125, 0.56843089, 0.02603361, 0.26741206],
       [0.70212059, 0.46794669, 0.07078713, 0.99305221, 0.65945498,
        0.90206976, 0.36400869, 0.05669531, 0.57361583, 0.20471413],
       [0.11616569, 0.5866954 , 0.08708842, 0.83380692, 0.53793678,
        0.13858748, 0.97510093, 0.79935653, 0.14225394, 0.08684159]])

array([[1.45233713],
       [1.61873996],
       [1.85664825],
       [0.86734006],
       [2.00172108],
       [1.22998699],
       [1.73604632],
       [0.96770527],
       [1.30373892],
       [0.06738592],
       [0.52526631],
       [1.05929367],
       [1.46890574],
       [2.0128999 ],
       [0.68896066],
       [1.83004636],
       [0.82281379],
       [0.98180824],
       [0.41770862],
       [1.9245851 ],
       [1.28315974],
       [1.7232522 ],
       [1.52280007],
       [0.99533481],
       [1.10286588],
       [0.04198799],
       [0.20967351],
       [1.52840789],
       [0.34377831],
       [1.46930229],
       [0.24460109],
       [0.2870478 ],
       [0.50537671],
       [1.14540221],
       [1.70937833],
       [0.53928255],
       [1.71625826],
       [0.9467213 ],
       [1.45633996],
       [1.68386963],
       [1.73005861],
       [1.44206366],
       [1.31439674],
       [0.94915984],
       [1.42334005],
       [0.80963313],
       [1.31087087],
       [1.793